import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import { Task } from '../types';

export interface AiMessage {
    id: string;
    role: 'user' | 'assistant';
    content: string;
    timestamp: number;
    attachments?: {
        type: 'file' | 'link';
        id: string;
        name: string;
        url: string;
        metadata?: any;
    }[];
    suggestions?: Task[]; // For draft tasks generated by AI
    isThinking?: boolean;
    thoughts?: string; // AI's internal reasoning (Stream of Thought)
}

interface AiState {
    messages: AiMessage[];
    isAssistantOpen: boolean;
    isProcessing: boolean;

    // Actions
    addMessage: (message: Omit<AiMessage, 'id' | 'timestamp'>) => string;
    updateMessage: (id: string, updates: Partial<AiMessage>) => void;
    clearMessages: () => void;
    toggleAssistant: (isOpen?: boolean) => void;
    setProcessing: (isProcessing: boolean) => void;
    getLatestAssistantMessage: () => AiMessage | undefined;
}

export const useAiStore = create<AiState>()(
    persist(
        (set, get) => ({
            messages: [],
            isAssistantOpen: false,
            isProcessing: false,

            addMessage: (message) => {
                const id = Math.random().toString(36).substring(7);
                set((state) => ({
                    messages: [
                        ...state.messages,
                        {
                            ...message,
                            id,
                            timestamp: Date.now(),
                        }
                    ].slice(-50)
                }));
                return id;
            },

            updateMessage: (id, updates) => set((state) => ({
                messages: state.messages.map((msg) =>
                    msg.id === id ? { ...msg, ...updates } : msg
                )
            })),

            clearMessages: () => set({ messages: [] }),

            toggleAssistant: (isOpen) => set((state) => ({
                isAssistantOpen: isOpen !== undefined ? isOpen : !state.isAssistantOpen
            })),

            setProcessing: (isProcessing) => set({ isProcessing }),

            getLatestAssistantMessage: () => {
                const assistantMessages = get().messages.filter(m => m.role === 'assistant');
                return assistantMessages[assistantMessages.length - 1];
            },
        }),
        {
            name: 'ai-assistant-storage',
            partialize: (state) => ({ messages: state.messages }), // Only persist messages
        }
    )
);
